### ISSUE TITLE
I will add support for Adis16490 

### ISSUE THREAD

**Issue by messplay** [tork-a/adi_driver#11]
Hi I think that a few changes in maping register is possible. Do you have some recomendations?

**Comment by 7675t** [comment]
Hi, Could you clarify your point? I believe ADIS16490 is also similar to ADIS16470, while I'm not sure they are identical. Anyway it is not so difficult to adapt the package to ADIS16490. If you have the device, please try to make it work by yourself and send a PR. When you have concrete question or problem, we can support you as possible. Thank you :smile:

**Comment by 7675t** [comment]
Hey, it is a big difference :nerd_face: Our code depends on the USB-IIS module which use PIC and has original command system as an ACM device. I didn't know MCP2210. It looks also good to use, but I don't have the one. If you want to use that module, you need to rewrite almost all the communication methods.

I know current package should be organized not to depend on the communication device, but is takes some time and currently we recommend to use USB-IIS. It is handy because no device driver needed.

**Comment by messplay** [comment]
Well just now(19:41 GMT-5) I am rewriting src/16xxx.cpp file to setup with new module, appear be very similar just changing SPI config commands (however I will buy IIS, just in case =)

**Comment by 7675t** [comment]
Great, please send PR if you ready!

**Comment by messplay** [comment]
Well I have one question why in code always you use 0x61 in `buff[0] = 0x61;` is custom I read in 16470 datasheet but I did not have an answer.

**Comment by 7675t** [comment]
No, it is not the spec of ADIS16470, it is spec of USB-IIS. USB-IIS need a command byte on the top. Please consult [USB-ISS datasheet](https://www.robot-electronics.co.uk/htm/usb_iss_spi_tech.htm).

**Comment by 7675t** [comment]
Please reopen if you have further questions.
